name: flutter_radar_animation

description: A customizable Flutter package for radar sweep animations with various styles, including gradients, shapes, and pulse effects.
version: 1.0.2
homepage: https://github.com/ahmedmandur/flutter_radar_animation
repository: https://github.com/ahmedmandur/flutter_radar_animation
issue_tracker: https://github.com/ahmedmandur/flutter_radar_animation/issues
documentation: https://github.com/ahmedmandur/flutter_radar_animation/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
